Traceback (most recent call last):
  File "/home/users/esmith88/roocs/character_scanner/scanner_test.py", line 150, in <module>
    main()
  File "/home/users/esmith88/roocs/character_scanner/scanner_test.py", line 146, in main
    make_json(args)
  File "/home/users/esmith88/roocs/character_scanner/scanner_test.py", line 53, in make_json
    ds = xr.open_mfdataset(nc_files)
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.5.11/envs/jaspy3.7-m3-4.5.11-r20181219/lib/python3.7/site-packages/xarray/backends/api.py", line 595, in open_mfdataset
    raise IOError('no files to open')
OSError: no files to open
